### ISSUE TITLE
Thank you!!

### ISSUE THREAD

**Issue by olliecheng** [atar-wace-archive/atar-wace-archive.github.io#1]
Didn't quite know how to contact you so this looks like the best way to go - you're an absolute legend! Y12 this year, this is incredible.

Well done on your ATAR & have fun at uni :)

**Comment by peter-tanner** [comment]
I just saw this, thanks for the support :)
If you find any pdfs for missing marking keys feel free to open an issue (still missing a lot from the pre-ATAR/2016 period)
Hopefully your year 12 experience is smoother than ours. Having only a short lockdown in the middle of the year seems better/less disruptive than last year's scenario. I mean, it affected all years but it really messed with some year 12 specific stuff for our school anyways.

Good luck, and if you ever need chemistry/physics tech tips feel free to email me (I just added it to my profile - forgot that's not public)
* One last thing: going to add the 2020 papers once all courses have done making them public - probably will wait a month or two for that
